### PR TITLE
fix: helm v4 compatibility

### LINKED ISSUE #977: Helmsman v4.0.1 fails with Helm v4.0.0: "unknown flag: --client" error (Support for Helm v4.x.x)
On November 12, 2025, Helm v4.0.0 was released. We are using Helmsman v4.0.1, and when running it with Helm v4.0.0, we encounter the following error:

```
| |        | | 
| |__   ___| |_ __ ___  ___ _ __ ___   __ _ _ __
| '_ \ / _ \ | '_ ` _ \/ __| '_ ` _ \ / _` | '_ \ 
| | | |  __/ | | | | | \__ \ | | | | | (_| | | | | 
|_| |_|\___|_|_| |_| |_|___/_| |_| |_|\__,_|_| |_| version: v4.0.1
A Helm-Charts-as-Code tool.

2025-11-13 15:25:01 CRITICAL: While checking helm version: Checking Helm version failed with non-zero exit code 1: exit status 1
output: 
--- stdout ---

--- stderr ---
Error: unknown flag: --client
```

It appears Helmsman is passing the --client flag to Helm, which is no longer supported in Helm v4.0.0. Please advise on compatibility and include in the backlog a fix 🙏.

Steps to reproduce:

Install Helm v4.0.0.
Run Helmsman v4.0.1.
Expected behavior:
Helmsman should work with Helm v4.0.0 without errors.

Actual behavior:
Fails with "unknown flag: --client".

Environment:

Helmsman version: v4.0.1
Helm version: v4.0.0
Date observed: November 13, 2025

### PR DESCRIPTION
**Pull request by luisdavim**
This should fix #977

### CODE REVIEW

File: internal/app/helm_helpers.go [hunk 1]
```diff
@@ -13,6 +13,10 @@ import (
 	"github.com/mkubaczyk/helmsman/internal/gcs"
 )
 
+// TOOD: this is to avoid shelling out multiple times to get the version,
```
Comment (mkubaczyk) [inline internal/app/helm_helpers.go]:
```suggestion
// TODO: this is to avoid shelling out multiple times to get the version,
```

**Review by mkubaczyk — APPROVED** [review]
LGTM, just noticed one typo in comment. Thanks @luisdavim, feel free to merge
